name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDE2NGFkMjctOWIwNi00OWEyLTliODYtNmE1YTAzMzljM2YxIiwidGVuYW50X2lkIjoiZjUwOTgwNjFiZmMxOTIyZTVhZjM3YWZmZDEyMmZhMzY3YmQ0Zjc5MGY4YjJiNTZlYTkxZGZiNGJkMmI0ZGExOCIsImludGVybmFsX3NlY3JldCI6IjA1ZDM1ZTE1LTQ3NDUtNDQ1Yi05OGYxLWRkZTg5MGViOGRlNCJ9.2LAuT76X2LS44Fm0c2LyyhjAiMTb8NW4nyIijsMdTC8"
JWT_SECRET="Aritra@123"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1